### ISSUE TITLE
Assertion violation during a Map update in Firefly

### ISSUE THREAD

**Issue by gtrepta** [kframework/llvm-backend#339] opened 2020-05-28 19:41 UTC
One of the commits after dbe669b6fe32db5da7c936dcfbe4618e64570b14 seems to have created an issue for Firefly when executing one of its rules at `coverage.md:180`.

It can be reproduced by checking out Firefly and running the following:
```
git submodule update deps/evm-semantics
cd deps/evm-semantics
git checkout 7ef36b57
git submodule update --init --recursive -- deps/
cd -
make deps
make build-firefly-web3
git submodule update --init --recursive -- tests/demos/leap-contracts
make tests/demos/leap-contracts/.prep
make tests/demos/leap-contracts/.demo
```

**Comment by dwightguth** [comment] 2020-06-09 15:28
Duplicate of #343

**Closed by dwightguth** 2020-06-09 15:28 UTC
